import type { Metadata } from "next";

import FooterLinks from "@/app/auth/components/FooterLinks";

import Form from "./components/Form";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div>
      <Form />
      <FooterLinks
        links={[
          { title: "Sign in", href: "/auth" },
          { title: "Create new account", href: "/auth/registration" },
        ]}
      />
    </div>
  );
}
