version: "3"

networks:
  billing-network:
    driver: bridge

services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: donotusemyrootpassword
    logging:
      driver: none
    networks:
      - billing-network
    ports:
      - 27017:27017
    volumes:
      - ~/mongo/data:/data/db

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: donotusemyrootpassword
      ME_CONFIG_MONGODB_URL: mongodb://root:donotusemyrootpassword@mongo:27017/
    depends_on:
      - mongo
    logging:
      driver: none
    networks:
      - billing-network

  billing:
    image: therealguriev/service-billing:c748f18f714c6d139c53ea644754c61ef9a59d15
    restart: unless-stopped
    depends_on:
      - mongo
    logging:
      driver: none
    networks:
      - billing-network
    environment:
      NITRO_MONGO_URI: "mongodb://root:donotusemyrootpassword@mongo:27017/"
      NITRO_SECRET: "secret"

  gateway:
    image: therealguriev/service-gateway:5041a92cb129abc74288e9a4e5e4f757ab3fdd6d
    ports:
      - "3000:3000"
    environment:
      NITRO_SECRET: "secret"
      NITRO_ROUTES_FILE: "/routes.json"
    volumes:
      - ./routes.json:/routes.json
    depends_on:
      - mongo-express
      - billing
    networks:
      - billing-network

  front:
    image: therealguriev/billing:cb105fd682f963018dd52952e8d2ff449d205e46
    ports:
      - "80:3000"
    environment:
      API_URL: "http://gateway:3000"
    networks:
      - billing-network

