import { Suspense } from "react";

import { Wallet } from "ethers";
import type { Metadata } from "next";

import Form from "./components/Form";
import LogoutHandler from "./components/LogoutHandler";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Page() {
  const wallet = Wallet.createRandom();
  return (
    <div>
      <Form initialMnemonic={String(wallet.mnemonic?.phrase)} />
      <Suspense fallback={null}>
        <LogoutHandler />
      </Suspense>
    </div>
  );
}
