import { Wallet } from "ethers";
import type { Metadata } from "next";

import Form from "./components/Form";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Page() {
  const wallet = Wallet.createRandom();
  return (
    <div>
      <Form initialMnemonic={String(wallet.mnemonic?.phrase)} />
    </div>
  );
}
