import type { Metadata } from "next";

import FooterLinks from "./components/FooterLinks";
import Form from "./components/Form";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div>
      <Form />
      <FooterLinks
        links={[
          { title: "Forgot password?", href: "/auth/forgot-password" },
          { title: "Create new account", href: "/auth/registration" },
        ]}
      />
    </div>
  );
}
