import type { Metadata } from "next";
import Link from "next/link";

import { Button } from "@/components/ui/button";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div className="flex flex-col gap-4">
      <h1 className="text-2xl">Success</h1>
      <h3 className="text-sm">
        We just sent a recovery code to your email. Please use the provided link
        to recover your password.
      </h3>
      <Button variant="outline" name="home" asChild>
        <Link href="/auth">Home</Link>
      </Button>
    </div>
  );
}
